---
import:
  - "~/.config/alacritty/colors.yml"

env:
  TERM: xterm-256color

window:
  opacity: 0.9
  dimensions:
    columns: 160
    lines: 48
  padding:
    x: 16
    y: 16
  decorations: buttonless

font:
  normal:
    family: "Fira Code"
    style: Regular
  bold:
    family: "Fira Code"
    style: Bold
  size: 12.0

bell:
  animation: EaseOutExpo
  color: '0xffffff'
  duration: 0

live_config_reload: true

draw_bold_text_with_bright_colors: true

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

cursor:
  style:
    shape: Beam
    blinking: Always
  blink_interval: 500
  unfocused_hollow: true
  thickness: 0.15

shell:
  program: /usr/local/bin/tmux
  args:
    - new-session

key_bindings:
  - {key: Right, mods: Alt, chars: "\x1BF"}
  - {key: Left, mods: Alt, chars: "\x1BB"}
