import:
  - "~/.config/alacritty/kanagawa-dragon.yml"

env:
  TERM: xterm-256color
  WINIT_X11_SCALE_FACTOR: "1"

window:
  option_as_alt: Both
  dimensions:
    columns: 140
    lines: 60
  padding:
    x: 6
    y: 6
  decorations: buttonless

font:
  normal:
    family: FiraCode Nerd Font Mono
    style: Regular
  bold:
    family: FiraCode Nerd Font Mono
    style: Bold
  size: 11.5

bell:
  animation: EaseOutExpo
  duration: 0

live_config_reload: true

draw_bold_text_with_bright_colors: true

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

cursor:
  style:
    shape: Beam
    blinking: Always
  thickness: 0.1
  blink_interval: 500
  vi_mode_style:
    shape: Beam

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux"

key_bindings:
  - { key: Right, mods: Alt, chars: "\eF" }
  - { key: Left, mods: Alt, chars: "\eB" }
  # C-a - split vertically (top/bottom)
  - { key: D, mods: Command|Shift, chars: "\x01-" }
  # C-a ! split horizontally (left/right)
  - { key: D, mods: Command, chars: "\x01!" }
