---
import:
  - "~/.config/alacritty/colors.yml"

env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 160
    lines: 48

font:
  normal:
    family: "Fira Code"
    style: Regular

bell:
  animation: EaseOutExpo
  duration: 0

live_config_reload: true

cursor:
  style:
    shape: Beam
    blinking: Always
  blink_interval: 500

shell:
  program: /usr/local/bin/tmux
  args:
    - new-session

key_bindings:
  - {key: Right, mods: Alt, chars: "\x1BF"}
  - {key: Left, mods: Alt, chars: "\x1BB"}
