import = ["~/.config/alacritty/themes/kanagawa.toml"]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 750
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "beam"

[cursor.vi_mode_style]
blinking = "on"
shape = "beam"

[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.normal]
family = "FiraCode Nerd Font Mono"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["--login", "-c", "tmux new-session -A -s main"]
program = "/usr/local/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1
startup_mode = "Maximized"

[window.dimensions]
columns = 140
lines = 80

[window.padding]
x = 6
y = 6
