session_name: dbt
start_directory: "${HOME}/pgy-projects"
environment:
  ENV: prod
  AWS_PROFILE: Eng-Prod
windows:
  - window_name: dbt-snowflake
    start_directory: dbt-luigi/DBT_piperdb
  - window_name: dbt-spark
    start_directory: dbt-luigi/dbt-luigi-spark
  - window_name: config
    start_directory: config
