session_name: dev
environment:
  ENV: prod
  AWS_PROFILE: Eng-Prod
windows:
  - window_name: dbt-snowflake
    start_directory: "${HOME}/pgy-projects/dbt-luigi/DBT_piperdb"
  - window_name: dbt-spark
    start_directory: "${HOME}/pgy-projects/dbt-luigi/dbt-luigi-spark"
  - window_name: dotfiles
    start_directory: "${HOME}/.dotfiles"
    layout: main-horizontal

