# What protocol to use when performing git operations.
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc.
editor:
# When to interactively prompt.
prompt: enabled
# A pager program to send command output to, e.g. "less"
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
