#! /usr/bin/env zsh

# Options

# Set general options.
typeset -ga zopts_general=(
	NO_BEEP
	INTERACTIVE_COMMENTS
	EXTENDED_GLOB
)

# Set job options.
typeset -ga zopts_job=(
	LONG_LIST_JOBS # List jobs in the long format by default.
	NO_BG_NICE     # Don't run all background jobs at a lower priority.
	NO_CHECK_JOBS  # Don't check for changed jobs immediately.
	NO_HUP         # Don't kill jobs on shell exit.
)

# Set completion options.
typeset -ga zopts_completion=(
	ALWAYS_TO_END    # When completing from the middle of a word, move the cursor to the end of the word.
	AUTO_MENU        # Show completion menu on a single tab press.
	AUTO_NAME_DIRS   # Automatically add a trailing slash to directory names.
	COMPLETE_IN_WORD # Allow completion from within a word.
  LIST_PACKED      # List all matches for an ambiguous pattern.
)

# Set directory options.
typeset -ga zopts_directory=(
	AUTO_CD            # Change to a directory without typing cd.
)

# Set history options.
typeset -ga zopts_history=(
	APPEND_HISTORY         # Append history lines to the history file rather than overwrite it.
	EXTENDED_HISTORY       # Write the history file in the ":start:elapsed;command" format.
	INC_APPEND_HISTORY     # Write to the history file immediately, not when the shell exits.
	SHARE_HISTORY          # Share history between all sessions.
	HIST_EXPIRE_DUPS_FIRST # Expire duplicate entries first when trimming history.
	HIST_IGNORE_DUPS       # Don't record an entry that was just recorded again.
	HIST_IGNORE_ALL_DUPS   # Delete old recorded entry if new entry is a duplicate.
	HIST_FIND_NO_DUPS      # Do not display a line previously found.
	HIST_IGNORE_SPACE      # Don't record an entry starting with a space.
	HIST_SAVE_NO_DUPS      # Don't write duplicate entries in the history file.
	HIST_REDUCE_BLANKS     # Remove superfluous blanks before recording entry.
	HIST_VERIFY            # Don't execute immediately upon history expansion.
)

# Set all configured options
setopt $zopts_general \
	$zopts_job \
	$zopts_completion \
	$zopts_directory \
	$zopts_history
