#! /usr/bin/env zsh
# vim: set fdm=marker:

typeset -ga opts_general=(
	LONG_LIST_JOBS # Display PID when suspending processes as well.
	PROMPT_SUBST   # Expansions are performed in prompts.
	NO_BEEP        # Don't beep on errors.
)

typeset -ga opts_history=(
	BANG_HIST              # Treat the '!' character specially during expansion.
	EXTENDED_HISTORY       # Save each command's epoch timestamps and the duration in seconds.
	HIST_EXPIRE_DUPS_FIRST # Expire duplicate entries first when trimming history.
	HIST_FIND_NO_DUPS      # Don't display a line previously found.
	HIST_IGNORE_ALL_DUPS   # Delete old recorded entry if new entry is a duplicate.
	HIST_IGNORE_DUPS       # Don't record an entry that was just recorded again.
	HIST_IGNORE_SPACE      # Don't record an entry starting with a space.
	HIST_REDUCE_BLANKS     # Remove superfluous blanks before recording an entry.
	HIST_SAVE_NO_DUPS      # Don't write duplicate entries in the history file.
	HIST_VERIFY            # Don't execute the line directly instead perform history expansion.
	INC_APPEND_HISTORY     # Write to the history file immediately, not when the shell exits.
	SHARE_HISTORY          # Share history between all sessions.
)

typeset -ga opts_directories=(
	AUTO_CD           # If can't execute the directory, perform the cd command to that.
	AUTO_PUSHD        # Make cd push the old directory onto the directory stack.
	NO_CDABLE_VARS    # Don't expand arguments given to a cd command.
	NO_CHASE_DOTS     # Don't resolve symbolic links upon path segments.
	NO_CHASE_LINKS    # Don't resolve symbolic links upon changing directories.
	NO_POSIX_CD       # Make cd command POSIX incompatible.
	PUSHD_IGNORE_DUPS # Don't push multiple copies of the same directory onto the stack.
	PUSHD_MINUS       # Exchanges  the  meanings of `+` and `-` for pushd.
	PUSHD_SILENT      # Do not print the directory stack after pushd or popd.
	PUSHD_TO_HOME     # Have pushd with no arguments act like `pushd $HOME`.
)

typeset -ga opts_completion=(
	COMPLETE_ALIASES # Prevent aliases from being substituted before completion is attempted.
	COMPLETE_IN_WORD # Attempt to start completion from both ends of a word.
	GLOB_COMPLETE    # Don't insert anything resulting from a glob pattern, show completion menu.
	NO_LIST_BEEP     # Don't beep on an ambiguous completion.
	LIST_PACKED      # Try to make the completion list smaller by drawing smaller columns.
	MENU_COMPLETE    # Instead of listing possibilities, select the first match immediately.
)

typeset -ga opts_globbing=(
	BRACE_CCL          # Expand expressions in braces which would not otherwise undergo brace expansion.
	EXTENDED_GLOB      # Treat the `#`, `~` and `^` characters as part of patterns for globbing.
	GLOB_DOTS          # Don't require a leading '.' in a filename to be matched explicitly.
	MAGIC_EQUAL_SUBST  # Unquoted arguments of the form `key=value` have filename expansion performed.
	MARK_DIRS          # Append a trailing `/` to all directory names resulting from globbing.
	NO_NOMATCH         # If a pattern has no matches, don't print an error, leave it unchanged.
)

typeset -ga opts_io=(
	NO_CLOBBER           # Don't allow `>` redirection to override existing files. Use `>!` instead.
	NO_FLOW_CONTROL      # Disable flow control characters `^S` and `^Q`.
	NO_IGNORE_EOF        # Enable ^D to logout, exit on end-of-file.
	INTERACTIVE_COMMENTS # Allow comments even in interactive shells.
	RM_STAR_WAIT         # Before executing `rm *` first wait 10 seconds and ignore anything typed.
)

# Set all configured options
setopt $opts_general \
	$opts_history \
	$opts_directories \
	$opts_completion \
	$opts_globbing \
	$opts_io
